#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service()
{
    mkdir -p /var/log/ha
    procd_open_instance
    procd_set_param command hass --config /etc/homeassistant --log-file /var/log/ha/home-assistant.log --log-rotate-days 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-70} ${respawn_timeout:-5} ${respawn_retry:-5}
    # use HUP to reload
    procd_set_param reload_signal HUP
    # terminate using signals
    procd_set_param term_timeout 60
    procd_close_instance
}
